spring.jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql : true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://
  username:
  password:
  platform: postgres
  diver-class-name: org.postgresql.Driver

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000
